//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankingAppDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public string AccountID { get; set; }
        public string AccountType { get; set; }
        public string CustomerID { get; set; }
        public string OpenedBy { get; set; }
        public string OpenedByRole { get; set; }
        public System.DateTime OpenDate { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual FixedDepositAccount FixedDepositAccount { get; set; }
        public virtual LoanAccount LoanAccount { get; set; }
        public virtual SavingsAccount SavingsAccount { get; set; }
    }
}
