//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankingAppDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FixedDepositAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FixedDepositAccount()
        {
            this.FixedDepositTransactions = new HashSet<FixedDepositTransaction>();
        }
    
        public string FDAccountID { get; set; }
        public string CustomerID { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public decimal FD_ROI { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> MaturityAmount { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FixedDepositTransaction> FixedDepositTransactions { get; set; }
    }
}
