//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankingAppDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FixedDepositTransaction
    {
        public int TransactionID { get; set; }
        public string FDAccountID { get; set; }
        public string TransactionType { get; set; }
        public decimal Amount { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
    
        public virtual FixedDepositAccount FixedDepositAccount { get; set; }
    }
}
