//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankingAppDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manager
    {
        public string ManagerID { get; set; }
        public string ManagerName { get; set; }
        public string PAN { get; set; }
    }
}
